version: "3.6"
services:
  jdk-server:
    image: acolasz/weblogic-base:${FMW_VERSION}
    build:
      context: .
      args:
        artifactory_url: "https://artifactory.dorsum.eu/artifactory"
        artifactory_user: "user"
        artifactory_password: "psw"
        tech_user: "acolasz"
        jdk_u_version: "${U_VERSION}"
        fmw_version: "${FMW_VERSION}"
        